image: node:stretch-slim

cache:
  paths:
    - node_modules/

before_script:
  - rm -rf dist
  - CI=false npm install

build:
  stage: deploy
  script:
    - CI=false npm run build
  artifacts:
    paths:
      - dist
  only:
    - master