image: node:stretch-slim

cache:
  paths:
    - node_modules/

before_script:
  - rm -rf dist
  - CI=false npm install

static:
  stage: build
  script:
    - CI=false npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  only:
    - master

pages:
  stage: deploy
  script:
    - CI=false npm run build
    - rm -rf public
    - cp dist/index.html
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master